### ISSUE TITLE
SAF Documentation: Property table not displayed in full width

### ISSUE THREAD

**Issue by andreasniggl** [StructuralAnalysisFormat/gitbookdocumentation#41]
Dear SAF-Team,
With the current Documentation on www.saf.guide, in encounter the issue that the property tables are not displayed in their full width. Changing the size of the browser does not change the width of the property table. See the picture attached. I encounter that on Google Chrome as well as on MS Edge.

<img width="929" alt="SAF Property Table on MS Edge" src="https://user-images.githubusercontent.com/33835650/141978706-7cce0143-616e-488e-b479-0a35d7802d3d.PNG">
.
Thanks & best regards
Andreas

**Comment by dschuermans** [comment]
Hey @andreasniggl, this is a known issue we've been trying to solve for a while now.
We're trying to come up with solutions, but we can't control how GitBook renders markdown tables as far as we know 😞 

So we'd either have to come up with a different way of explaining the object's properties or use something else then GitBook

**Comment by andreasniggl** [comment]
Hi @dschuermans, thanks, I assumed you have it on your list. It's just a little bit cumbersome always to scroll down, scroll right and scroll up to just read the description :-).

**Comment by dschuermans** [comment]
Hey @andreasniggl 
This is being tracked by #26 ;)

I've been looking at readthedocs.io, how does [this](https://gitbookdocumentation.readthedocs.io/en/latest) look like to you?

**Comment by dschuermans** [comment]
@andreasniggl just an fyi, we've updated the docs to readthedocs and released it yesterday 😄

**Comment by andreasniggl** [comment]
Hi @dschuermans looks really nice now! Very convenient to read and browse.  For example with the alternating colours in the tables. Thanks!
